name: app_mobile_iot
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  google_nav_bar: ^5.0.6
  http: ^1.2.2
  flutter_appauth: ^8.0.1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/favicon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
